"""Subclass of FormBox, which is generated by wxFormBuilder."""

import wx
import demo

# Implementing FormBox
class DemonstracaoFormBox( demo.FormBox ):
	def __init__( self, parent ):
		demo.FormBox.__init__( self, parent )

app=wx.App()
frame=DemonstracaoFormBox(None)
frame.Show(True)
app.MainLoop()

