"""Subclass of FormBox, which is generated by wxFormBuilder."""

import wx


# Implementing FormBox
from modulo02 import demo


class DemonstracaoFormBox( demo.FormBox ):
	def __init__( self, parent ):
		demo.FormBox.__init__( self, parent )

app=wx.App()
frame=DemonstracaoFormBox(None)
frame.Show(True)
app.MainLoop()

